org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.11

maven_group=dev.yoima
archives_base_name=OBS-Recording-Monitor

fabric_version=0.152.1+26.2
fabric_key_mapping_version=2.0.5+e2bdee789c
modmenu_version=20.0.0-beta.2
