package dev.yoima.reccheck.obs;

public enum ObsIssueKind {
	NONE,
	OBS_NOT_RUNNING,
	OBS_UNREACHABLE,
	WRONG_PORT_OR_HOST,
	AUTH_FAILED,
	WEBSOCKET_DISABLED,
	INVALID_CONFIG,
	NETWORK_ERROR,
	PROTOCOL_ERROR,
	UNKNOWN
}
